###########
# site.title, site.url, site.author.name

title:   'schroeder-blog.de'
author:
  name:  'Steffen Schr√∂der'

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false
